
POST http://localhost:5000/api/equipment/create
Content-Type: application/json

{
  "Name": "Scale of the Bronze Tyrant",
  "Description": "It shimmers and glows in certain light",
  "Tags": {
    "Rarity": "VERY_RARE",
    "EquipmentType": "ARMOR",
    "RequiresAttunement": true
  },
  "OnReaction": [
    {
      "Name": "Electric Discharge",
      "Description": "When hit, the wielder can choose to release a shockwave of lightning energy around them in a 10 ft. radius. Creatures in the radius must make a DC 14 Dex Save or take **1d6 Lightning Damage** per charge used or half as much on a save. When this feature is used, it cannot be used until the next short rest."
    }
  ],
  "Effects": [
    "AC is 16 + Dex Modifier (maximum of 2)",
    "Disadvantage on Stealth Checks",
    "When struck with an attack that would deal damage, gain 1 charge.",
    "While the armor has charges, gain resistance to Lightning Damage."
  ],
  "ResetsOn": "ALWAYS"
}


###

GET http://localhost:5000/api/equipment/all

### 
GET http://localhost:5000/api/equipment?name=Scale%20of%20the%20Bronze%20Tyrant
Content-Type: application/json


